In [1]:
# Illustate 2D convolution of images through an example
import scipy.signal
import numpy as np

In [2]:
image = np.array([[1,2,3,4,5,6,7],
                 [8, 9, 10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19, 20, 21],
         [22, 23, 24, 25, 26, 27, 28],
         [29, 30, 31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40, 41, 42],
         [43, 44, 45, 46, 47, 48, 49]])

In [3]:
# Defined an image-processing kernel
filter_kernel = np.array([[-1,1,-1],
                          [-2,3,1],
                         [2,-4,0]])

In [4]:
# Convolve the image with the filter kernel through scipy 2D convolution to produce an
#output image of same dimension as that of the input
I = scipy.signal.convolve2d(image, filter_kernel, mode ='same', boundary = 'fill', fillvalue=0)
print(I)

[[ -2  -8  -7  -6  -5  -4  28]
 [  5  -3  -4  -5  -6  -7  28]
 [ -2 -10 -11 -12 -13 -14  28]
 [ -9 -17 -18 -19 -20 -21  28]
 [-16 -24 -25 -26 -27 -28  28]
 [-23 -31 -32 -33 -34 -35  28]
 [-29  13  13  13  13  13  27]]


        We replicate the logic of a scipy 2D convolution by going through the following steps 
     a) The boundaries need to be extended in both directions for the image and padded with zeroes.
      For convolving the 7x7 image by 3x3 kernel, the dimensions need to be extended by
    (3-1)/2—i.e., 1—
    #on either side for each dimension. So a skeleton image of 9x9 image would be created
     in which the boundaries of 1 pixel are pre-filled with zero.
     b) The kernel needs to be flipped—i.e., rotated—by 180 degrees
     c) The flipped kernel needs to placed at each coordinate location for the image and then
    the sum of
    coordinate-wise product with the image intensities needs to be computed. These sums for
    each coordinate would give
    the intensities for the output image.

In [5]:
row,col = 7,7
#Rotate the filter kernel twice by 90 degrees to get 180 rotation
filter_kernel_flipped = np.rot90(filter_kernel,2)
## Pad the boundaries of the image with zeroes and fill the rest from the original image
image1 = np.zeros((9,9))
for i in range(row):
    for j in range(col):
        image1[i+1, j+1] = image[i,j]
print(image1)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  0.]
 [ 0.  8.  9. 10. 11. 12. 13. 14.  0.]
 [ 0. 15. 16. 17. 18. 19. 20. 21.  0.]
 [ 0. 22. 23. 24. 25. 26. 27. 28.  0.]
 [ 0. 29. 30. 31. 32. 33. 34. 35.  0.]
 [ 0. 36. 37. 38. 39. 40. 41. 42.  0.]
 [ 0. 43. 44. 45. 46. 47. 48. 49.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [7]:
filter_kernel_flipped

array([[ 0, -4,  2],
       [ 1,  3, -2],
       [-1,  1, -1]])

In [6]:
# Define the output image
image_out = np.zeros((row,col))
# Dynamic shifting of the flipped filter at each image coordinate and then computing the
# convolved sum.
for i in range(1,1+row):
    for j in range(1,1+col):
        arr_chunk = np.zeros((3,3))
        
        for k,k1 in zip(range(i-1,i+2), range(3)):
            for l,l1 in zip(range(j-1,j+2), range(3)):
                arr_chunk[k1,l1] = image1[k,l]
            
        image_out[i-1,j-1] = np.sum(np.multiply(arr_chunk,filter_kernel_flipped))
    
print(image_out)
#zip make the iterations in two list

[[ -2.  -8.  -7.  -6.  -5.  -4.  28.]
 [  5.  -3.  -4.  -5.  -6.  -7.  28.]
 [ -2. -10. -11. -12. -13. -14.  28.]
 [ -9. -17. -18. -19. -20. -21.  28.]
 [-16. -24. -25. -26. -27. -28.  28.]
 [-23. -31. -32. -33. -34. -35.  28.]
 [-29.  13.  13.  13.  13.  13.  27.]]


In [10]:
# the convolution operation fz in this mode
ss = np.array([[0,0,0],[0,1,2],[0,8,9]])
tt = np.multiply(ss,filter_kernel_flipped)

In [12]:
np.sum(tt)

-2